version: "3"

services:
  backend-app:
    build:
      context: src/.
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    env_file:
      - .env
    ports:
      - 4001:3000
    networks:
      - backend-app-network
    volumes:
      - database-migrations:/app/database/migrations

networks:
  appss-statistics-network:
    driver: bridge

volumes:
  database-migrations:
    driver: local
